import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Toaster } from "sonner";
const OutfitFont = Outfit({
  subsets: ["latin"],
}); 

export const metadata = {
  title: "SkillSphere",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${OutfitFont.className} h-full antialiased`}
    >
      <body>
        <Navbar></Navbar>
          <Toaster position="top-right" richColors></Toaster>
          {children} 
        <Footer></Footer>
      </body>
    </html>
  );
}
